<a href="https://colab.research.google.com/github/ronenbendavid/IDC_NLP/blob/master/Notebook_2_Pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed




In [0]:
import torch

Construct a 5x3 tensor, uninitialized:



In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[5.6554e-38, 0.0000e+00, 6.5268e-38],
        [0.0000e+00, 6.5268e-38, 0.0000e+00],
        [1.9603e+29, 0.0000e+00, 3.0354e+32],
        [1.8174e+31, 0.0000e+00, 0.0000e+00],
        [5.6482e-11, 7.2735e+22, 5.0023e-40]])


Construct a randomly initialized matrix:



In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5449, 0.1989, 0.4570],
        [0.7202, 0.7419, 0.0409],
        [0.7577, 0.7395, 0.3696],
        [0.2795, 0.6193, 0.1494],
        [0.9156, 0.5919, 0.0124]])


Construct a matrix filled zeros and of dtype long:



In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6799, -0.6289, -0.5200],
        [ 1.4009,  1.5352,  0.9227],
        [ 1.6855,  1.7873, -1.5526],
        [ 0.8831, -2.3540, -1.0153],
        [-1.2654, -1.0267, -0.1325]])


Get its size:



In [0]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [0]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3871,  0.2709,  0.2182],
        [ 1.5823,  1.5943,  1.2503],
        [ 2.5802,  2.4947, -1.2172],
        [ 1.0676, -1.8424, -0.9909],
        [-1.0910, -0.6210,  0.6095]])


Addition: syntax 2



In [0]:
print(torch.add(x, y))

tensor([[ 1.3871,  0.2709,  0.2182],
        [ 1.5823,  1.5943,  1.2503],
        [ 2.5802,  2.4947, -1.2172],
        [ 1.0676, -1.8424, -0.9909],
        [-1.0910, -0.6210,  0.6095]])


Addition: providing an output tensor as argument



In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3871,  0.2709,  0.2182],
        [ 1.5823,  1.5943,  1.2503],
        [ 2.5802,  2.4947, -1.2172],
        [ 1.0676, -1.8424, -0.9909],
        [-1.0910, -0.6210,  0.6095]])


Addition: in-place



In [0]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3871,  0.2709,  0.2182],
        [ 1.5823,  1.5943,  1.2503],
        [ 2.5802,  2.4947, -1.2172],
        [ 1.0676, -1.8424, -0.9909],
        [-1.0910, -0.6210,  0.6095]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [0]:
print(x[:, 1])

tensor([-0.6289,  1.5352,  1.7873, -2.3540, -1.0267])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3377])
0.3377150297164917


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

> See how changing the np array changed the Torch Tensor automatically



In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# AUTOGRAD: AUTOMATIC DIFFERENTIATION

Central to all neural networks in PyTorch is the autograd package. Let’s first briefly visit this, and we will then go to training our first neural network.

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

Let us see this in more simple terms with some examples.

torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.

To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

To prevent tracking history (and using memory), you can also wrap the code block in with torch.no_grad():. This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don’t need the gradients.

There’s one more class which is very important for autograd implementation - a Function.

If you want to compute the derivatives, you can call .backward() on a Tensor. If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), however if it has more elements, you need to specify a gradient argument that is a tensor of matching shape.


In [0]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [0]:
print(y.grad_fn)

In [0]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


.requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.

In [0]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


Let’s backprop now. 



In [0]:
out.backward() # when nothing passed in, it means like if we passed 1

In [0]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [0]:
x = torch.randn(3, requires_grad=True)

print('x=', x)
y = x ** 2

print('y=', y)

x= tensor([-0.1587,  0.7416, -0.9704], requires_grad=True)
y= tensor([0.0252, 0.5499, 0.9417], grad_fn=<PowBackward0>)


In [0]:
gradients = torch.tensor([2, 2, 2], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([-0.6348,  2.9662, -3.8816])


You can also stop autograd from tracking history on Tensors with .requires_grad=True by wrapping the code block in with torch.no_grad():

In [0]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
